### ISSUE TITLE
Bokeh Bar Plots are easier to make than presented

### ISSUE THREAD

**Issue by bryevdv** [dovinmu/python-viz-notebooks#1]
Bokeh *can* convert DataFrames directly:

<img width="933" alt="screen shot 2018-04-26 at 08 34 10" src="https://user-images.githubusercontent.com/1078448/39315889-a0873c3c-492c-11e8-8760-98aa5f31288e.png">

I'd also comment out that the `output_notebook` is a single time command that typically happens once at the top of a notebook, so the actual relevant comparable code for the bat chart is just:
```
p = figure(x_range=list(large_cities.index),  toolbar_location=None)
p.vbar(x='AccentCity', top='Population', width=0.9, source=largest_cities,  
       line_color='white')
p.xaxis.major_label_orientation = "vertical"

show(p)
```

Categorical support in general got a large update late last year, please see:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

**Comment by bryevdv** [comment]
@dovinmu I would make a PR but it would not make sense to update the code without also updating the editorial content around the code, which is best left to you.

**Comment by bryevdv** [comment]
Also worth mentioning:
```
p.xaxis.major_label_orientation = "vertical"
```
works to obtain vertical labels as well

**Comment by dovinmu** [comment]
@bryevdv Finally getting around to addressing this (took me a while because I needed to update a bunch of dependencies for the code to run properly). Mind if I give you a shout-out in the references section of the notebook?

**Comment by bryevdv** [comment]
Certainly, that would be fine, thanks!
